### ISSUE TITLE
合并带数字签名的发票会导致数字印章丢失

### ISSUE THREAD

**Issue by liujunwei4321** [pymupdf/PyMuPDF-Utilities#10]
合并带数字签名的发票（比如话费发票）会导致数字印章丢失。

**Comment by JorjMcKie** [comment]
I cannot read Chinese - sorry. Please stick to English!
Google gives me this translation of your text:
> Merging invoices with digital signatures (such as phone bills) will result in the loss of digital seals.

Is this correctly translated?
If yes, then my answer would be this:
1. This is **_normal!_** A PDF with digital signature must not be changed - except via incremental updates. Merging PDF's therefore will result in the loss of the signature.
2. This is not related to PyMuPDF.

Closing this issue. If I misunderstood you, please open a new issue in the main repository (PyMuPDF). In English please.
