### ISSUE TITLE
Suggestion for Jupyter notebooks

### ISSUE THREAD

**Issue by Lucas-C** [pymupdf/PyMuPDF-Utilities#101]
Hi!

Thank you for providing Jupyter notebooks as examples 😊
I was able to quickly import one in Google Colab:
https://colab.research.google.com/github/pymupdf/PyMuPDF-Utilities/blob/master/jupyter-notebooks/new-circle-annot.ipynb

I have a couple of suggestions regarding them:

* maybe add this as a first cell, to automatically install `PyMuPDF`?
```
!!pip install pymupdf
```

* maybe add this as the last cell of all notebooks, in order to allow downloading the PDF generated ?
```python
from base64 import b64encode
from IPython.display import display, HTML
base64_pdf = b64encode(doc.tobytes()).decode("utf-8")
# Diplay a download button:
display(HTML(f'<a download="PyMuPDF-example.pdf" href="data:application/pdf;base64,{base64_pdf}">Click to download PDF</a>'))
```

**Comment by JorjMcKie** [comment]
That's a good idea - although I would put the installation as a comment inside a markdown cell as opposed to unconditionally execute it.

**Comment by JorjMcKie** [comment]
Thanks for your comment anyway. Question: can the notebook be **_executed_** in this environment?

**Comment by Lucas-C** [comment]
> Thanks for your comment anyway. Question: can the notebook be **_executed_** in this environment?

In Google Colab? Yes absolutely!
