### ISSUE TITLE
ModuleNotFoundError: No module named 'ParseTab'

### ISSUE THREAD

**Issue by DeepDiverGuy** [pymupdf/PyMuPDF-Utilities#102]
I ran this script & found this error. Then, tried to install it using PIP, but there is no module named 'ParseTab' anywhere. Searched Github, nothing! Searched on the Internet, there is absolutely no information about "ParseTab". As a result, the script has become useless. I have latest version of PyMuPDF installed.

**Comment by JorjMcKie** [comment]
> "this script"

look [here](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/extract-table)

**Comment by DeepDiverGuy** [comment]
thanks for the fast response
