### ISSUE TITLE
anonymize.py raises UnicodeDecodeError

### ISSUE THREAD

**Issue by stefan6419846** [pymupdf/PyMuPDF-Utilities#109]
Apparently https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/examples/anonymize-document/anonymize.py supports both Python 2 and Python 3, while PyMuPDF dropped Python 2 support quite some time ago. This seems to lead to some issues when running the script itself:

```python3
Traceback (most recent call last):
  File "/home/stefan/cwd/redact.py", line 51, in <module>
    stream = remove_txt(stream)
  File "/home/stefan/cwd/redact.py", line 25, in remove_txt
    cont1 = (cont.decode()).replace("\n", " ")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x9c in position 502: invalid start byte
```

It is not really clear to me when this example stopped working or whether this affects some documents only. In my case, I switched to byte-strings directly instead of doing any conversions, which seemed to fix it:

```python3
def remove_txt(cont):
    """
    Remove everything enclosed in a pair of "BT" / "ET" strings, including both.
    Assuming "cont" is the string of a PDF "/Contents" stream, this will make
    all text of the owning page disappear (permanent delete).
    """
    cont1 = cont.replace(b"\n", b" ")
    ct = cont1.split(b" ")
    nct = []
    intext = False
    for word in ct:
        if word == b"ET":
            intext = False
            continue
        if word == b"BT":
            intext = True
            continue
        if intext:
            continue
        nct.append(word)

    ncont = b" ".join(nct)
    return ncont
```

**Comment by JorjMcKie** [comment]
Thanks for bringing this up.
Your repair of the code should have been implemented like that from the beginning, because the `/Contents` objects are always `bytes` in PyMuPDF.

**Comment by JorjMcKie** [comment]
I am going to close this here.
As mentioned, we are not maintaining the scripts in this repository by way of fixing issues.
Instead, if a user wants to contribute something, we gladly accept PRs to improve example scripts.
