### ISSUE TITLE
Resolution of PDF in example/doc-browser.py

### ISSUE THREAD

**Issue by Knightowl3128** [pymupdf/PyMuPDF-Utilities#11]
What is the best way to get better resolution of the final render? I want to get something as comparable to Sumatra reader (as shown in the image), but I can't figure out how to do this. I guess resizing a 2x scaled render is the best way to go about it but I'm not sure how to implement it.  Any help would be appreciated :)

![image](https://user-images.githubusercontent.com/58213848/120105345-2c643b00-c176-11eb-849c-847be2363fb2.png)

**Comment by JorjMcKie** [comment]
You already have found the `doc-browser.py` script, which contains the ability to zoom into a page - however at a fixed constant rate: the available window for page content in zooming mode, can be used for showing one of the 3 x 3 parts of the original page.

Look at the logic to achieve zooming: Use a matrix `mat = fitz.Matrix(zoom, zoom)` when making a pixmap: `page.get_pixmap(matrix=mat,...)`.
The `zoom` factor is a float which magnifies (or shrinks) if >1 or <1. So if zoom=2 then magnification is 200% etc.
Assuming your display window has the dimensions WIDTH and HEIGHT, and the sub-rectangle of the page you want to show is `rect = fitz.Rect(x0, y0, x1, y2)`, then do this to calculate the correct zoom factor:

```python
if rect.width / rect.height < WIDTH / HEIGHT:
    zoom = HEIGHT / height
else:
    zoom = WIDTH / width
mat = fitz.Matrix(zoom, zoom)
pix = page.getPixmap(matrix=mat, clip=rect, alpha=False)
```

**Comment by Knightowl3128** [comment]
I'm aware on how to achieve zoom by changing the fitz.matrix. But, what I'm asking is how to get a better resolution at 1x Zoom as shown in the image, where Sumatra gives a better resolution than the doc-browser. If I do a 2x Zoom, I can get a better resolution but I can only see a part of the PDF. I'm a beginner at all of this and I'm confused on how to work with tkinter to fit a higher resolution image to the display window where every part is visible. I hope you understood.

**Comment by JorjMcKie** [comment]
I understand. I am not sure either.
You can try the following things:
* change the image format handed to tkinter from "ppm" to "png" and hope this will trigger TK using a different algorithm.
* simply use a larger zoom factor (e.g. twice at large than computed in previous post) and then see what TK does with it.
* if the preceeding doesn't work, use Pillow's `thumbnail` to shrink the image so it fits into TK's window. But after first try, the previous seemss to work ...

**Comment by JorjMcKie** [comment]
Just looked up Pillow again.
You can do e.g. this:
* compute the pixmap with a doubled zoom factor
* convert it to a Pillow Image `img`, and then use `img.resize(size, resample=3, box=None, reducing_gap=1)`. Play with the `resample` and `reducing_gap` values to meet your requirements.

**Comment by Knightowl3128** [comment]
> Just looked up Pillow again.
> You can do e.g. this:
> 
> * compute the pixmap with a doubled zoom factor
> * convert it to a Pillow Image `img`, and then use `img.resize(size, resample=3, box=None, reducing_gap=1)`. Play with the `resample` and `reducing_gap` values to meet your requirements.
> 
> set size =(img.width//2, img.height//2) to restore the original dimensions.

I've tried this and it doesn't work. The final quality is the same as when I just used a zoom factor of 1. I guess I have to read more about downscaling an image. Here's the sample code which I've used:

```
import fitz
from PIL import Image

pdf = fitz.open('test.pdf')
page_number = 5
page = pdf.loadPage(page_number)

scaling_matrix = fitz.Matrix(2, 2)
pix = page.getPixmap(matrix=scaling_matrix, alpha=False)

img = Image.frombytes('RGB', [pix.width, pix.height], pix.samples)
img.show()
img = img.resize((img.width // 2, img.height // 2),resample=3, box=None, reducing_gap=1)
img.show() 
```

**Comment by Knightowl3128** [comment]
I found the solution and it has to do with [scaling in Microsoft Windows and DPI awareness.](https://stackoverflow.com/questions/61150615/why-does-tkinter-canvas-widget-show-images-at-a-wrong-scale?noredirect=1&lq=1) The solution is to set DPI awareness by adding this in the code.

```
import ctypes

ctypes.windll.shcore.SetProcessDpiAwareness(2)
```

**Comment by JorjMcKie** [comment]
Woah! How interesting - never heard of this before.
Thansk for digging this out!
