### ISSUE TITLE
libcrypt.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Aidenren1215** [pymupdf/PyMuPDF-Utilities#112]
tried the find_table jupyter notebook, but can't import fitz in notebook. the error message is as the title. I saw read.me file, it said that pymupdf == 1.23.0 has feature find_table, I also tried in my macbook, but can't install the latest version of package.

**Comment by JorjMcKie** [comment]
Version 1.23.0 is just about to be released. Pleased be patient for another day or two!

**Comment by Aidenren1215** [comment]
Thanks! Looking forward to seeing new features in the package.

**Comment by JorjMcKie** [comment]
Version 1.23.3 came out which should fix your problem.
