### ISSUE TITLE
document rescale after replacing fonts

### ISSUE THREAD

**Issue by hbghlyj** [pymupdf/PyMuPDF-Utilities#117]
Emoji fonts in the following PDF are not embedded, so it is blank when opened in PDF viewer:
[google-Noto+Colr+Emoji+Glyf-v14.html.pdf](https://github.com/pymupdf/PyMuPDF-Utilities/files/13257643/google-Noto%2BColr%2BEmoji%2BGlyf-v14.html.pdf)

Using `repl-font.py` to replace fonts, the result is too small (Shrunk to the upper left corner)
<img src="https://github.com/pymupdf/PyMuPDF-Utilities/assets/53823634/765eaccb-6795-4563-8a53-e435a56578ef" width="600">
The content of `google-Noto+Colr+Emoji+Glyf-v14.html.pdf-fontnames.json` is
```json
[
  {
    "oldfont": [
      ""
    ],
    "newfont": "cjk",
    "info": "Not embedded!"
  }
]
```
For comparison, the result of using Adobe Acrobat "Edit pdf" to replace fonts with "Segoe UI Emoji" is
<img src="https://github.com/pymupdf/PyMuPDF-Utilities/assets/53823634/9681dd89-f6b0-4494-b02c-2eaca6cb9412" width="600">

**Comment by JorjMcKie** [comment]
As mentioned in the disclaimer of this repository, we do not accept issues for the examples.
They are intended to help you creating your application, but you still are responsible to adjust them as needed.
