### ISSUE TITLE
how to deal with Chinese?

### ISSUE THREAD

**Issue by lrybbbccc** [pymupdf/PyMuPDF-Utilities#142]
I tried to use this script:
"https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/examples/convert-document)
/convert.py"
to convert a Chinese file from .txt to .pdf, but the output is full of garbled code. 
What can I do to fix this problem?

**Comment by JorjMcKie** [comment]
We do not accept issue submissions in this repository - consult the README please.
Apart from that I don't understand, why you chose that particular example for your task. It converts an EBOOK!
Why don't you use direct support for text documents as explained in the documentation?
