### ISSUE TITLE
text-extraction/fitzcli.py: layout mode fails with index access error

### ISSUE THREAD

**Issue by mara004** [pymupdf/PyMuPDF-Utilities#15]
```
Traceback (most recent call last):
  File "fitzcli.py", line 1145, in <module>
    main()
  File "fitzcli.py", line 1141, in main
    args.func(args)  # execute requested command
  File "fitzcli.py", line 833, in gettext
    func[args.mode](
  File "fitzcli.py", line 753, in page_layout
    rows = curate_rows(rows, GRID)
  File "fitzcli.py", line 612, in curate_rows
    nrows = [rows[0]]
IndexError: list index out of range
```

The affected document is private and not permitted for sharing, unfortunately. However, it is a scanned book that consists of many pages with a 2 on 1 layout (left and right side). The OCR layer was added with ocrmypdf.

**Comment by mara004** [comment]
This issue equally affects the fitz module's command-line tool.
I also found another document of similar structure which triggered the same error.

**Comment by JorjMcKie** [comment]
Just uploaded a revised version.
Also extended the example files: there is one now with shadowed characters, which look extremely silly when extracted via naive text extractions.

**Comment by mara004** [comment]
Wow, thanks!
