### ISSUE TITLE
newdoc.insertpdf()

### ISSUE THREAD

**Issue by Larbo53** [pymupdf/PyMuPDF-Utilities#17]
Hello,

I want to split a document containing several invoices into as many files as there are invoices. These are identified by their number.

hear is my code :
def decoupe_fichier(Siret,doc):
#prend un fichier et le découpe en autant de numéro de facture différents
    Num_page=0
    Num_fact=0
    rec=[]
    Fournisseur=''
    n=Nb_page_traitees(Siret,doc)
    New_doc = fitz.open()
    sql="SELECT Code_fournisseurs,X0,Y0,X1,Y1 FROM Schema_recup_Data WHERE  Nom_colonne='Num_facture' AND Siret='"+ Siret+"'" #récupére le rectangle contenant le num facture
    curs1.execute(sql)
    for row in curs1:        
        Fournisseur=row[0]
        for pag in doc.pages(0,doc.pageCount, 1): # parcourt le nombre de pages du document ouvert.
            Num_fact=page.get_textbox([row[1],row[2],row[3],row[4]])
            if pag.get_textbox([row[1],row[2],row[3],row[4]])==Num_fact: #controle par page du num de facture
                
                Num_page+=1
            else:
                print(pag.number)
                print(pag.get_textbox([row[1],row[2],row[3],row[4]]))
                New_doc.insert_pdf(doc, from_page=pag.number-1, to_page=Num_page-1)
                New_doc.save(path+'/'+Fournisseur+Num_fact+'pdf')
                New_doc.close()

the error returned is :
Traceback (most recent call last):
  File "/Users/yves/Recup-Z-interface-compta/BenoitCastel/programme-py/test_extrait_detail_facture_10Aout2021.py", line 322, in <module>
    decoupe_fichier(Siret,doc)
  File "/Users/yves/Recup-Z-interface-compta/BenoitCastel/programme-py/test_extrait_detail_facture_10Aout2021.py", line 295, in decoupe_fichier
    New_doc.insert_pdf(doc, from_page=pag.number-1, to_page=Num_page-1)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/fitz/fitz.py", line 4282, in insert_pdf
    raise ValueError("document closed or encrypted")
ValueError: document closed or encrypted

Thanks a lot for your help.
Sincerely.

**Comment by JorjMcKie** [comment]
Your code is hard to read because the indentation is missing for the most part.
Anyway, as the message says: one of the twoPDFs, `doc` or `newdoc` is not available. As you probably never close the source document `doc`, it must be `newdoc`.

**Comment by Larbo53** [comment]
thanks a lot.

I join my code.
[newdoc-insert_pdf.pdf](https://github.com/pymupdf/PyMuPDF-Utilities/files/6988738/newdoc-insert_pdf.pdf)

**Comment by JorjMcKie** [comment]
Oops - closed already?
From what I have seen in your code, once you have written one invoice to `newdoc`, you close it, but never open it again for the next invoice in your source document.
This seems to be the reason.

Another tip:
To communicate source code in this thread, either attach it as a zipped file - `source.py.zip`, which makes it easy to use it for others, or put it in a message directly here by encapsulating it with the two lines like so:
![grafik](https://user-images.githubusercontent.com/8290722/129491249-f4d505d1-f278-4f6f-a2d4-6f71291b1046.png)

**Comment by Larbo53** [comment]
Thanks a lot From france.

Sincerely

**Comment by Larbo53** [comment]
Hi,

How to open again a newdoc after close the one invoice to newdoc. I dont where i must put the command.

Here is my code with zip.
[newdoc-insert_pdf.py.zip](https://github.com/pymupdf/PyMuPDF-Utilities/files/6989942/newdoc-insert_pdf.py.zip)
sincerely.

**Comment by JorjMcKie** [comment]
[newdoc-insert_pdf.zip](https://github.com/pymupdf/PyMuPDF-Utilities/files/6990385/newdoc-insert_pdf.zip)
I think here ...

**Comment by Larbo53** [comment]
Thank you very much, but this code creates only one file for the first invoice whereas it should create more than twenty. I attach the file : deroche-non-empty.pdf

Sincerely.
[deroche-non-empty.pdf](https://github.com/pymupdf/PyMuPDF-Utilities/files/6990440/deroche-non-empty.pdf)

**Comment by JorjMcKie** [comment]
Well, your code is wrong then, isn't it.
I don't understad what you are doing with all that Sqlite stuff, but anyway. Here is a script that correctly processes the example file at least. You owe me something ...
[splitter.zip](https://github.com/pymupdf/PyMuPDF-Utilities/files/6991990/splitter.zip)

**Comment by Larbo53** [comment]
Thank you. The presence of Sqlite is explained by the fact that the function is part of a set of functions, one of which is to identify the lines to be extracted from an invoice. All products in an invoice are subject to VAT, so the rectangle containing the VAT code is used as a test field by comparing the content with a list of VAT code values (see attached function).
[test_zone_test.py.zip](https://github.com/pymupdf/PyMuPDF-Utilities/files/6993838/test_zone_test.py.zip)

**Comment by JorjMcKie** [comment]
ok, I understand.
Yiu may have seen that I realized the invoice number is on a fixed place on every page. So I used that rectangle to determine, if the current page is the first of the next invoice.
Then let's close this - it did not involve any PyMuPDF issue anyway.

**Comment by Larbo53** [comment]
Good evening,

sorry. Indeed I should have closed this request.

Thank you.

Sincerely

**Comment by JorjMcKie** [comment]
no problem
