### ISSUE TITLE
extract text from rectangle

### ISSUE THREAD

**Issue by Larbo53** [pymupdf/PyMuPDF-Utilities#21]
Good morning,

please find attached:
- the pdf file with the areas to be extracted,
- the identification of the test area (screen copy)
- the small test python program
- the value returned in the python ide
I don't understand why the returned text is like this.

Thanks for your help.

Sincerely
[Z sorbier janvier 2021.pdf](https://github.com/pymupdf/PyMuPDF-Utilities/files/7237406/Z.sorbier.janvier.2021.pdf)
Capture d’écran 2021-09-27 à 17.06.58.png
Capture d’écran 2021-09-27 à 17.06.23.png

program test python:
import fitz  #pymupdf
import sqlite3

path='/Users/yves/Downloads'
source = path+'/Z sorbier janvier 2021.pdf'
conn=sqlite3.connect('/Users/yves/Recup-Z-interface-compta/BenoitCastel/Benoit_Z.db')
curs1=conn.cursor()
sql="SELECT Libel_zone,X0,Y0,Large,Hauteur FROM Parametre_recup_Z where Code_societe='SORBIER'"
curs1.execute(sql)
base_recup = curs1.fetchall() #retourne par rubrique les zones à extraire

Code_societe=''
Periode=''

with fitz.open(source) as doc:
    rec=(base_recup[0][1],base_recup[0][2],base_recup[0][1]+base_recup[0][3],base_recup[0][2]+base_recup[0][4])
    Code_societe=doc[0].get_textbox(rec)
    rec1=(base_recup[1][1],base_recup[1][2],base_recup[1][1]+base_recup[1][3],base_recup[1][2]+base_recup[1][4])
    Periode=doc[0].get_textbox(rec1)
  rec=(236.2,80.69,301.91,98.29)
    print(rec)
    Valeur=doc[0].get_textbox(rec)
    print(Valeur)

**Comment by JorjMcKie** [comment]
Things like your case may happen. This is the "fault" of the PDF creator.
"Naive" text extraction like `page.get_text("text")` and `page.get_textbox(rect)` extract text in the sequence as the PDF creator has coded the file.
On occasion, you will even find arbitrary permutations of each single character - without any obvious problem when looking at the page using a PDF viewer. But when you select the text and copy/paste it to eg. Word, you will see chaos - like it is your case.
This is how it looks like when copy / pasting the text in wordmusing a normal PDF viewer:
![grafik](https://user-images.githubusercontent.com/8290722/134944701-9dc7df10-64e5-42a9-ad27-ae052f2572db.png)


You have few options:
1. select the single characters contained in the rectangle of interest and then sort them by ascending x-coordinate
2. OCR the full page (or just the rectangle) and then extract the text

**Comment by Larbo53** [comment]
thank you very much for this almost instantaneous response.

Sincerely.

**Comment by Larbo53** [comment]
Hi,

Solution 1:

Valeur=doc[0].get_textbox(rec3).split()
        texte=''
        for j in range(len(Valeur)-1,-1,-1):
            texte+=Valeur[j]

Sincerely

Yves Larbodiere
EVARD
3, rue des Courtes Terres
95220 HERBLAY
portable : 07 81 08 41 00
mail : ***@***.***

**Comment by JorjMcKie** [comment]
Yes, works ... in **_this_** case, just by chance and because you knew the problem beforehand.
But look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/textmaker2.pdf). It looks exactly equal to [this](https://github.com/pymupdf/PyMuPDF-Utilities/blob/master/text-extraction/textmaker.pdf) one.
Nonetheless, naive text extraction will produce chaos from the first one ...
BTW both were created using PyMuPDF.

**Comment by JorjMcKie** [comment]
To cover the general case, you could do this:
```python
clip = fitz.Rect(...) # the rectangle within which your data are
chars = []  # store characters from within clip here
for b in page.get_text("rawdict", clip=clip)["blocks"]:
    for l in b["lines"]:
        for s in l["spans"]:
            for c in s["chars"]:
                chars.append((c["origin"], c["c"]))  # store bottom-left char coord and the char itself
chars.sort(key=lambda c: c[0][0])  # sort by ascending x-coordinate
text = "".join([c[1] for c in chars])  # should reconstruct your text
```
