### ISSUE TITLE
Extract PDF page Image Lose Color

### ISSUE THREAD

**Issue by frideal** [pymupdf/PyMuPDF-Utilities#22]
Hi,Ineed some some help,

When I try import images form PDF file

I find some image become some color loss,

![image](https://user-images.githubusercontent.com/3777883/135008769-27cf5480-168f-4dab-900d-78a10ca43cb5.png)

origin target page looks like:
![image](https://user-images.githubusercontent.com/3777883/135008881-46138522-a487-413e-85c4-2706b83de1e1.png)

this is my test pdf file:
[9骆驼618.pdf](https://github.com/pymupdf/PyMuPDF/files/7240331/9.618.pdf)

page9  , page 16 some of imge is right, 

i use pymupdf utilities

```
def recoverpix(doc, item):
    xref = item[0]  # xref of PDF image
    smask = item[1]  # xref of its /SMask

    # special case: /SMask or /Mask exists
    if smask > 0:
        pix0 = fitz.Pixmap(doc.extract_image(xref)["image"])
        mask = fitz.Pixmap(doc.extract_image(smask)["image"])
        pix = fitz.Pixmap(pix0, mask)
        if pix0.n > 3:
            pix = fitz.Pixmap(fitz.csRGB, pix)

        return {  # create dictionary expected by caller
            "ext": "png",
            "colorspace": pix.colorspace.n,
            "image": pix.tobytes(),
        }

    # special case: /ColorSpace definition exists
    # to be sure, we convert these cases to RGB PNG images
    if "/ColorSpace" in doc.xref_object(xref, compressed=True):
        pix = fitz.Pixmap(doc, xref)
        pix = fitz.Pixmap(fitz.csRGB, pix)
        return {  # create dictionary expected by caller
            "ext": "png",
            "colorspace": 3,
            "image": pix.tobytes("png"),
        }
    return doc.extract_image(xref)

pageitemindex = 0
for pageitem in page_data_objects:
    pageblocks = pageitem.get_text("dict")["blocks"]
    pagepath = os.path.join(debug_out_put_folder, page_gen_data["genpages"][pageitemindex]["folder"])
    print("gen layout :" + pagepath)
    pageoutputfilename = "layout.json"
    pageitemindex = pageitemindex + 1

    xreflist = []
    dimlimit = 0  # 100  # each image side must be greater than this
    relsize = 0  # 0.05  # image : image size ratio must be larger than this (5%)
    abssize = 0  # 2048  # absolute image size limit 2 KB: ignore if smaller

    for imgnumber, img in enumerate(pageitem.getImageList(), start=1):
        xref = img[0]

        xref = img[0]
        if xref in xreflist:
            continue
        width = img[2]
        height = img[3]
        if min(width, height) <= dimlimit:
            continue
        image = recoverpix(document, img)
        n = image["colorspace"]
        imgdata = image["image"]

        if len(imgdata) <= abssize:
            continue
        if len(imgdata) / (width * height * n) <= relsize:
            continue

        imgfile = os.path.join(pagepath, "img%05i.%s" % (xref, image["ext"]))
        fout = open(imgfile, "wb")
        fout.write(imgdata)
        fout.close()
        xreflist.append(xref)


```

thanks.

**Comment by JorjMcKie** [comment]
**_This is not an issue of PyMuPDF._**

The example script must be adjusted:
The images you mention are JPEG images in CMYK color mode. They cannot be converted / saved as PNG images after they have been given an alpha channel: you must use a different extension "pam" to save them. If I do this and open the PAM image in Photoshop, it looks right.
I am going to modify the script - please look out.

**Comment by frideal** [comment]
hi, i wonder how to modfiy extract-image example and save png with alpha to local

when i try use 
```
def recoverpix(doc, item):
    xref = item[0]  # xref of PDF image
    smask = item[1]  # xref of its /SMask

    # special case: /SMask or /Mask exists
    if smask > 0:
        pix0 = fitz.Pixmap(doc.extract_image(xref)["image"])
        mask = fitz.Pixmap(doc.extract_image(smask)["image"])
        pix = fitz.Pixmap(pix0, mask)
        if pix0.n > 3:
            ext = "pam"
        else:
            ext = "png"

        return {  # create dictionary expected by caller
            "ext": ext,
            "colorspace": pix.colorspace.n,
            "image": pix.tobytes(ext),
        }

    # special case: /ColorSpace definition exists
    # to be sure, we convert these cases to RGB PNG images
    if "/ColorSpace" in doc.xref_object(xref, compressed=True):
        pix = fitz.Pixmap(doc, xref)
        pix = fitz.Pixmap(fitz.csRGB, pix)
        return {  # create dictionary expected by caller
            "ext": "png",
            "colorspace": 3,
            "image": pix.tobytes("png"),
        }
    return doc.extract_image(xref)
```

i can get right alpha channel in png.

**Comment by frideal** [comment]
> **_This is not an issue of PyMuPDF._**
> 
> The example script must be adjusted:
> The images you mention are JPEG images in CMYK color mode. They cannot be converted / saved as PNG images after they have been given an alpha channel: you must use a different extension "pam" to save them. If I do this and open the PAM image in Photoshop, it looks right.
> I am going to modify the script - please look out.

i try modified code ,but when i want to import png with alpha ,i just get png(RGB) files.


i look up for extract png with alpha in document , but i can't find right way to do this

**Comment by frideal** [comment]
if has a way to render page exclusive text?

i just want to save page without text to png files.

**Comment by JorjMcKie** [comment]
> i try modified code ,but when i want to import png with alpha ,i just get png(RGB) files.

What do you mean?
Take for example image at xref 380 (page 9). It has a mask of xref 381. If you combine the pixmaps and save the result as a PAM, then it can be correctly viewed by Photoshop. I found no other viewer which can display it, but ok.
You can also open the PAM file as a pixmap again.
But you cannot convert / save that pixmap to a PNG file. You can also not open that file as a PIL / pillow file.
Fact is, that image is CMYK with alpha channel - obviously rare.
That is all I can say.
```python
pix0 = fitz.Pixmap(doc.extract_image(380)["image"])
mask = fitz.Pixmap(doc.extract_image(381)["image"])
pix = fitz.Pixmap(pix0, mask)
pix.save("380.pam")

# open saved file as pixmap:
import fitz
pix = fitz.Pixmap("380.pam")
pix
Pixmap(DeviceCMYK, IRect(0, 0, 2226, 1245), 1)
```

**Comment by JorjMcKie** [comment]
> 
> 
> if has a way to render page exclusive text?
> 
> i just want to save page without text to png files.

Should be possible. Make a redaction annotation covering the whole page and then apply it without touching images. Then make a page pixmap.

**_But:_** If the text is part of the image (and not text in the PDF), then you have lost.
```python
import fitz
doc=fitz.open("9.618.pdf")
page=doc[8]
page.add_redact_annot(page.rect)
'Redact' annotation on page 8 of 9.618.pdf
page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)
True
pix=page.get_pixmap()
pix.save("page9.png")
```
![grafik](https://user-images.githubusercontent.com/8290722/135064670-0501804b-8908-43c5-8984-121aaa9fecf1.png)
This is also a way to avoid all these problems with different image extraction formats - if you are only interested in the page picture.

**Comment by frideal** [comment]
> > if has a way to render page exclusive text?
> > i just want to save page without text to png files.
> 
> Should be possible. Make a redaction annotation covering the whole page and then apply it without touching images. Then make a page pixmap.
> 
> **_But:_** If the text is part of the image (and not text in the PDF), then you have lost.
> 
> ```python
> import fitz
> doc=fitz.open("9.618.pdf")
> page=doc[8]
> page.add_redact_annot(page.rect)
> 'Redact' annotation on page 8 of 9.618.pdf
> page.apply_redactions(images=fitz.PDF_REDACT_IMAGE_NONE)
> True
> pix=page.get_pixmap()
> pix.save("page9.png")
> ```
> 
> ![grafik](https://user-images.githubusercontent.com/8290722/135064670-0501804b-8908-43c5-8984-121aaa9fecf1.png) This is also a way to avoid all these problems with different image extraction formats - if you are only interested in the page picture.

thanks so much, i will make a try.

**Comment by frideal** [comment]
when i try use this code to render entire page to png file, i find the font was missing?

this origin looking in pdf file
![image](https://user-images.githubusercontent.com/3777883/135212364-1f58ed43-a9d4-41c9-8075-dab30643caac.png)


i use
```       
       pagefullimagename = str(pageindex) + "_full_page.png"
        savefullimagefilepath = os.path.join(pageoutputfolderpath, pagefullimagename)
        mat = fitz.Matrix(zoom, zoom)
        fullpix = page.get_pixmap(matrix=mat)
        fullpix.save(savefullimagefilepath)
        print(savefullimagefilepath)

```
 output png file

![image](https://user-images.githubusercontent.com/3777883/135212459-78bd296b-77cc-42c3-a283-fc66b5f2535c.png)

**Comment by frideal** [comment]
font base name:('BINWDU+FZYAZT_TEJW--GB1-0', 'ttf', 'Type0', b'')
font base name:('BINWDU+FZCAIYT_TEJW--GB1-0', 'ttf', 'Type0', b'')
font base name:('AADQPW+STYuanti-SC-Regular', 'ttf', 'Type0', b'')
font base name:('AADQPW+FZKTK--GBK1-0', 'ttf', 'Type0', b'')
font base name:('AADQPW+STXinwei', 'ttf', 'Type0', b'')
font base name:('KaiTi', 'n/a', 'Type0', b'')
font base name:('IGFMXG+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('IGFMXG+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('AADQPW+FZY4K--GBK1-0', 'ttf', 'Type0', b'')
font base name:('XWZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('XWZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('RVROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('RVROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NPDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NPDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('EVROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('EVROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('VBFMXG+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('VBFMXG+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NKDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NKDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('UOVGJI+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('UOVGJI+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NKDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('NKDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('GBLAVK+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('GBLAVK+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('AFDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('AFDQPW+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('STBUHM+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('STBUHM+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('LPJENA+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('LPJENA+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('ELROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('ELROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('XCZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('XCZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('RGROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('RGROTO+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('KCZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')
font base name:('KCZYZC+FZLANTY_CUJW--GB1-0', 'cid', 'Type0', b'')

I found 
font base name:('KaiTi', 'n/a', 'Type0', b'')
n/a means is not embedded  font

**Comment by JorjMcKie** [comment]
>  n/a means is not embedded font

Exactly, the font used (KaiTi) on that page is not embedded, so each PDF viewer can decide how it renders it.
What you see is therefore how MuPDF renders it. Looks the same if you display the PDF with MuPDF's viewer.

**Comment by frideal** [comment]
> > n/a means is not embedded font
> 
> Exactly, the font used (KaiTi) on that page is not embedded, so each PDF viewer can decide how it renders it. What you see is therefore how MuPDF renders it. Looks the same if you display the PDF with MuPDF's viewer.

for pymupdf ,is there a way to "render" right image by page.get_pixmap ? or if i can use Page.insert_font before use page.get_pixmap to render out right page?
thanks

**Comment by JorjMcKie** [comment]
"Render right image" - what does that mean?

**Comment by frideal** [comment]
> "Render right image" - what does that mean?

Render Image Like we see  in the PDFViewer.

![image](https://user-images.githubusercontent.com/3777883/135223415-d8d258fe-c909-4bad-accc-7e81bf1e1de0.png)

**Comment by JorjMcKie** [comment]
No, the page will always look like every PDF viewer decides to do it. This is the fault of the PDF creator: he should have determined how exactly he wants stuff to look like. If he let others decide, then this may happen.
So for KaiTi there is no "right" way - or all ways to render the font are equally "right".
You can try and see if you can make a new PDF by replacing all or selected fonts. See the font replacement folder in this repo and experement a little if you want. Will not always work, but you may be lucky.

**Comment by JorjMcKie** [comment]
BTW Adobe Acrobat does it the same way as MuPDF. So you could argue that the PDFViewer you use it **_doing it wrong_**.

**Comment by frideal** [comment]
thanks i wil see font-replacement example

i wonder if it works by below steps?

do not replace font and generate new pdf file,
but just load real KAITI font stream and update to target xref stream

1. get xref of KAITI
2. udpate the xref stream of KAITI
3. apply
4. and use  page.get_pixmap to render target page

**Comment by JorjMcKie** [comment]
This is what font replacement will do for you

Jorj
