### ISSUE TITLE
Extract font files by fitzcli  problem.

### ISSUE THREAD

**Issue by frideal** [pymupdf/PyMuPDF-Utilities#24]
I tried 
```
python .\fitzcli.py extract -fonts e:\Lab\PyMuPDF-Utilities-master\PyMuPDF-Utilities-master\pdfresource\LUOTUO.pdf -output .\outputfolder
```

font files save to local file, but i can't open them in windows10's Font Viewer
![image](https://user-images.githubusercontent.com/3777883/136505544-e7e0ccca-3a82-4666-b87c-daaeecafbb54.png)

![image](https://user-images.githubusercontent.com/3777883/136506347-6f71cafa-d6ee-4e8b-b9e8-49344b6abe94.png)

**Comment by JorjMcKie** [comment]
Try to do font extraction with mutool extract.
If there is no change (which I do assume!), then that's that ...

**Comment by frideal** [comment]
> Try to do font extraction with mutool extract. If there is no change (which I do assume!), then that's that ...


![image](https://user-images.githubusercontent.com/3777883/136519930-71bd7315-8bbe-4d2a-a872-f201a459ffed.png)

Get the same result, can not open one of them by  windows10's Font Viewer

**Comment by JorjMcKie** [comment]
As suspected. Thanks for the info. There's nothing that can be done about it then.
