### ISSUE TITLE
Could you include an example in the collection doing pdf2png.py

### ISSUE THREAD

**Issue by joseberlines** [pymupdf/PyMuPDF-Utilities#25]
the title of the issue says it all.

I dont see the way to use the library converting pdf to png.
This question of mine in SO:
https://stackoverflow.com/questions/69643954/in-python-converting-pdf-to-png-with-python-without-pdf2image?noredirect=1#comment123104887_69643954

got an answer pointing to this library. The solution works but gets results with low resolution.

**Comment by JorjMcKie** [comment]
Look at [this](https://github.com/pymupdf/PyMuPDF-Utilities/tree/master/conversion) folder.
