### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by noblepriest** [pymupdf/PyMuPDF-Utilities#3]
Will this library supports for python 3+ versions? And I am getting syntax error for do_prompt.

_project.py", line 248
    do_prompt(d, "overwrite", "Overwrite existing file? (y/N)", "n", boolean)
            ^
SyntaxError: invalid syntax

**Comment by JorjMcKie** [comment]
@noblepriest - please be more specific: which script are you referring to?

**Comment by JorjMcKie** [comment]
closed for lack of interest
