### ISSUE TITLE
Searching for text

### ISSUE THREAD

**Issue by mameIIas** [pymupdf/PyMuPDF-Utilities#42]
I'm trying just a simple example where a couple of words are being replaced, but I can't replace a speficic word because the program doesn't work (the words commented are the ones that broke the code) (I'm trying to find Viviana but I can't). But if I write any other word it does work, that code does run, but if I change text it does not.
What can i do?

```
import fitz

### READ IN PDF
doc = fitz.open("input.pdf")

for page in doc:
    ### SEARCH
    text = "viiana"
    #text = "viviana"
    #text = "viana"
    text_instances = page.searchFor(text)

    ### HIGHLIGHT
    for inst in text_instances:
        highlight = page.addHighlightAnnot(inst)
        highlight.update()


### OUTPUT
doc.save("output.pdf", garbage=4, deflate=True, clean=True)
 ```

**Comment by JorjMcKie** [comment]
Please make a proper bug issue, including **_all mandatory data_**. Most importantly a reproducing file.
And please use the main repo. If your observations are correct (which I doubt), then this has nothing to do with the utilities repo.
The main repo has a bug report template which must be filled out completely to be acceptable.
