### ISSUE TITLE
Layout extraction issues

### ISSUE THREAD

**Issue by danielbichuetti** [pymupdf/PyMuPDF-Utilities#46]
We are facing some errors during layout extraction. On some PDFs, we are getting `RuntimeError: program error: minslot too small = 0`. I have taken a fast look over compute_slots and didn't see why it could be generating a slot with width 0. I found it happen on this line. Last written text is 637.

![image](https://user-images.githubusercontent.com/90110233/171737131-a08a547e-f5f7-4d69-9a5b-5740d2a6276f.png)

**Comment by JorjMcKie** [comment]
You did not provide any reproducible information.
But it may be a problem of these footnotes. Try to increase the minimum fontsize parameter.

**Comment by danielbichuetti** [comment]
Thank you, @JorjMcKie, for the help! I made a local version of your amazing code. Some PDF books are ill-formed indeed.
