### ISSUE TITLE
wxTableExtract position error

### ISSUE THREAD

**Issue by Buyabuyak** [pymupdf/PyMuPDF-Utilities#49]
Hello there,
I was trying the wxTableExtract example and the pdf was shifting when truing to add a rectangle.
It's working, but the shift makes a part of the pdf disappear behind the menu.

I managed to solve the problem by getting the pdf coordinates
pdfx, pdfy = self.PDFimage.GetPosition()
and adding them to the drawn or updated infos

in functions :
DrawRect --> dc.DrawRectangle(x + pdfx, y + pdfy, w, h)
DrawColumn --> dc.DrawLine(x + pdfx, self.rect_y + pdfy, x + pdfx, self.rect_y + self.rect_h + pdfy)
redraw_bitmap --> dc.DrawBitmap(bm, pdfx, pdfy)

Anyway, thanks again for the work !!!

**Comment by JorjMcKie** [comment]
Thanks for your appreciation.
As I wrote in the README: We do not accept issues here.
You are welcome to post a "Discussions" item and more than welcome submit a correction via a PR (pull request).
