### ISSUE TITLE
convert epub to pdf

### ISSUE THREAD

**Issue by njustczr** [pymupdf/PyMuPDF-Utilities#56]
I tried pdf-converter.py, but i found there maybe some messy code.
![image](https://user-images.githubusercontent.com/30426320/211141550-e7cfb081-8786-4917-839f-0327c281c696.png)
left is epub, right is pdf.
when i parsed the pdf,i got the result as the following image.
![image](https://user-images.githubusercontent.com/30426320/211141672-a556addc-e593-4770-9cd9-f5d7afe8d90e.png)

**Comment by JorjMcKie** [comment]
There is no way to follow up, if you do not include the problem file.
Can you please try out what the MuPDF CLI tool does?

`mutool draw -o output.pdf yourfile.epub` or `mutool convert ...`?

If there is a problem, then it exists in MuPDF.

**Comment by njustczr** [comment]
> There is no way to follow up, if you do not include the problem file. Can you please try out what the MuPDF CLI tool does?
> 
> `mutool draw -o output.pdf yourfile.epub` or `mutool convert ...`?
> 
> If there is a problem, then it exists in MuPDF.

I have tried mutool,but it got worse. 
I have upload the epub file. https://drive.google.com/file/d/1Cii9t1u-oaX7Z1UXgzpJyZbVy9AqG0-t/view?usp=sharing
The messy code is in the page 2,thanks.

**Comment by JorjMcKie** [comment]
You still did not communicate your OS, Python version and PyMuPDFor MuPDF version.
So reproducing the error is still not possible!
What has become clear at least is, that MuPDF viewers of the latest version 1.21.1 cannot display that file. Neither is it possible to convert it to any other format, whether PDF, text or whatever.
So you definitely should post a bug on MuPDF's issue management system https://bugs.ghostscript.com/enter_bug.cgi with all information.

**Comment by njustczr** [comment]
> You still did not communicate your OS, Python version and PyMuPDFor MuPDF version. So reproducing the error is still not possible! What has become clear at least is, that MuPDF viewers of the latest version 1.21.1 cannot display that file. Neither is it possible to convert it to any other format, whether PDF, text or whatever. So you definitely should post a bug on MuPDF's issue management system https://bugs.ghostscript.com/enter_bug.cgi with all information.

PyMuPDF 1.19.6
python 3.7
os: ubuntu18.04

**Comment by JorjMcKie** [comment]
@njustczr did you submit a bug report?
