### ISSUE TITLE
No support of /Filter /ASCIIHexDecode

### ISSUE THREAD

**Issue by angea** [pymupdf/PyMuPDF-Utilities#7]
I would like to turn any PDF into full ASCII via applying this filter on all streams.

I saw that mutool has an `clean -a` option to do so, but it doesn't do it automatically on every stream, which is odd.

I can't find any reference of ASCIIHexDecode on PyMuPDF or its utilities.
Am I missing something?

**Comment by JorjMcKie** [comment]
There is the ``ascii``  parameter in save / write.
But it simply passes it to MuPDF, ``mutool`` does exactly the same thing, because it neither is more than a code layer above MuPDF.

Have an example PDF where ascii conversion does not work?

**Comment by angea** [comment]
I tried on the official PDF specs `PDF32000_2008.pdf` - currently [here](https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf) - with no success.

**Comment by JorjMcKie** [comment]
This file is encrypted: copying is disabled. So I guess it doesn't count as an example ...

**Comment by JorjMcKie** [comment]
``mutool clean -a pdf_reference_1-7.pdf`` e.g. works (from https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf).

**Comment by angea** [comment]
Ah of course, stupid me...

Thanks!
