### ISSUE TITLE
Merge the demo scripts into the examples folder

### ISSUE THREAD

**Issue by programarivm** [pymupdf/PyMuPDF-Utilities#88]
For the sake of simplicity it may be good idea to merge all demo scripts into the examples folder at once.

**Comment by JorjMcKie** [comment]
Would not object to this. However, the problem in general is, that scripts are being referenced by URL in a lot other places, especially in the documentation on Read The Docs.
So every renaming and every relocation of a script has the potential to cause an internet 404 not found.
And this again causes pesky documentation bugs popping up all over the place.
So, actually all of these activities must be accompanied by locating the references and request respective change requests.

**Comment by programarivm** [comment]
See https://github.com/pymupdf/PyMuPDF-Utilities/issues/89
